### ISSUE TITLE
Bounty review

### ISSUE THREAD

**Issue by jernejpregelj** [iamonuwa/oceanprotocol-telegram-faucet-bot#1]
Hi @iamonuwa 

Great work! I tested the bot and it successfully sent ether.
There are still few things to improve:
- Section in readme with steps to setup the bot
- Tests to check endpoints (Telegram actions can be mocked)
- Fix last message on success or failure.

Image with current state of response messages:
![Screenshot 2019-03-14 at 18 09 03](https://user-images.githubusercontent.com/7147341/54377596-b7d07f00-4685-11e9-8541-2fb1682238da.png)

**Comment by iamonuwa** [comment]
Hi, @jernejpregelj, I'll fix the changes

**Comment by iamonuwa** [comment]
@jernejpregelj I've update the app
